version: '3'

volumes:
  vol-emqx-data:
    name: foo-emqx-data
    external: true
  vol-emqx-etc:
    name: foo-emqx-etc
    external: true
  vol-emqx-log:
    name: foo-emqx-log
    external: true

services:
  emqx4:
    image: emqx/emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node4.emqx.io"
    - "EMQX_ALLOW_ANONYMOUS=false"
    - "EMQX_ACL_NOMATCH=deny"
    - "EMQX_ACL_DENY_ACTION=disconnect"
    - "EMQX_ZONE__EXTERNAL__ACL_DENY_ACTION=disconnect"
    - "EMQX_ZONE__INTERNAL__ACL_DENY_ACTION=disconnect"
    - "EMQX_LOADED_PLUGINS=emqx_auth_pgsql"
    - "EMQX_AUTH__PGSQL__SERVER=192.168.100.58:5432"
    - "EMQX_AUTH__PGSQL__USERNAME=postgres"
    - "EMQX_AUTH__PGSQL__PASSWORD=postgres"
    - "EMQX_AUTH__PGSQL__DATABASE=postgres"
    - "EMQX_NODE__NAME=emqx@node4.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=mcast"
    - "EMQX_CLUSTER__MCAST__ADDR=239.192.0.1"
    - "EMQX_CLUSTER__MCAST__PORTS=4369,4370"
    - "EMQX_CLUSTER__MCAST__IFACE=0.0.0.0"
    - "EMQX_CLUSTER__MCAST__TTL=255"
    - "EMQX_CLUSTER__MCAST__LOOP=on"
    ports:
      - 60041:1883
      - 60042:8083
      - 60043:4369
      - 60044:18083
    networks:
      emqx-bridge:
        aliases:
        - node4.emqx.io
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

networks:
  emqx-bridge:
    driver: bridge