version: '3'

volumes:
  vol-emqx-data:
    name: foo-emqx-data
    external: true
  vol-emqx-etc:
    name: foo-emqx-etc
    external: true
  vol-emqx-log:
    name: foo-emqx-log
    external: true

services:
  emqx1:
    image: emqx/emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node1.emqx.io"
    - "EMQX_ALLOW_ANONYMOUS=false"
    - "EMQX_ACL_NOMATCH=deny"
    - "EMQX_ACL_DENY_ACTION=disconnect"
    - "EMQX_ZONE__EXTERNAL__ACL_DENY_ACTION=disconnect"
    - "EMQX_ZONE__INTERNAL__ACL_DENY_ACTION=disconnect"
    - "EMQX_LOADED_PLUGINS=emqx_auth_pgsql"
    - "EMQX_AUTH__PGSQL__SERVER=192.168.100.58:5432"
    - "EMQX_AUTH__PGSQL__USERNAME=postgres"
    - "EMQX_AUTH__PGSQL__PASSWORD=postgres"
    - "EMQX_AUTH__PGSQL__DATABASE=postgres"
    - "EMQX_NODE__NAME=emqx@node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=mcast"
    - "EMQX_CLUSTER__MCAST__ADDR=239.192.0.1"
    - "EMQX_CLUSTER__MCAST__PORTS=4369,4370"
    - "EMQX_CLUSTER__MCAST__IFACE=0.0.0.0"
    - "EMQX_CLUSTER__MCAST__TTL=255"
    - "EMQX_CLUSTER__MCAST__LOOP=on"
    ports:
      - 60011:1883
      - 60012:8083
      - 60013:4369
      - 60014:18083
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

  emqx2:
    image: emqx/emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node2.emqx.io"
    - "EMQX_ALLOW_ANONYMOUS=false"
    - "EMQX_ACL_NOMATCH=deny"
    - "EMQX_ACL_DENY_ACTION=disconnect"
    - "EMQX_ZONE__EXTERNAL__ACL_DENY_ACTION=disconnect"
    - "EMQX_ZONE__INTERNAL__ACL_DENY_ACTION=disconnect"
    - "EMQX_LOADED_PLUGINS=emqx_auth_pgsql"
    - "EMQX_AUTH__PGSQL__SERVER=192.168.100.58:5432"
    - "EMQX_AUTH__PGSQL__USERNAME=postgres"
    - "EMQX_AUTH__PGSQL__PASSWORD=postgres"
    - "EMQX_AUTH__PGSQL__DATABASE=postgres"
    - "EMQX_NODE__NAME=emqx@node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=mcast"
    - "EMQX_CLUSTER__MCAST__ADDR=239.192.0.1"
    - "EMQX_CLUSTER__MCAST__PORTS=4369,4370"
    - "EMQX_CLUSTER__MCAST__IFACE=0.0.0.0"
    - "EMQX_CLUSTER__MCAST__TTL=255"
    - "EMQX_CLUSTER__MCAST__LOOP=on"
    ports:
      - 60021:1883
      - 60022:8083
      - 60023:4369
      - 60024:18083
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

  emqx3:
    image: emqx/emqx:latest
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node3.emqx.io"
    - "EMQX_ALLOW_ANONYMOUS=false"
    - "EMQX_ACL_NOMATCH=deny"
    - "EMQX_ACL_DENY_ACTION=disconnect"
    - "EMQX_ZONE__EXTERNAL__ACL_DENY_ACTION=disconnect"
    - "EMQX_ZONE__INTERNAL__ACL_DENY_ACTION=disconnect"
    - "EMQX_LOADED_PLUGINS=emqx_auth_pgsql"
    - "EMQX_AUTH__PGSQL__SERVER=192.168.100.58:5432"
    - "EMQX_AUTH__PGSQL__USERNAME=postgres"
    - "EMQX_AUTH__PGSQL__PASSWORD=postgres"
    - "EMQX_AUTH__PGSQL__DATABASE=postgres"
    - "EMQX_NODE__NAME=emqx@node3.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY=mcast"
    - "EMQX_CLUSTER__MCAST__ADDR=239.192.0.1"
    - "EMQX_CLUSTER__MCAST__PORTS=4369,4370"
    - "EMQX_CLUSTER__MCAST__IFACE=0.0.0.0"
    - "EMQX_CLUSTER__MCAST__TTL=255"
    - "EMQX_CLUSTER__MCAST__LOOP=on"
    ports:
      - 60031:1883
      - 60032:8083
      - 60033:4369
      - 60034:18083
    networks:
      emqx-bridge:
        aliases:
        - node3.emqx.io
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

networks:
  emqx-bridge:
    driver: bridge